/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EjerciciosRouteImport } from './routes/ejercicios'
import { Route as ForoRouteImport } from './routes/foro'
import { Route as JuegosRouteImport } from './routes/juegos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RankingRouteImport } from './routes/ranking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EjerciciosRoute = EjerciciosRouteImport.update({
  id: '/ejercicios',
  path: '/ejercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ForoRoute = ForoRouteImport.update({
  id: '/foro',
  path: '/foro',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosRoute = JuegosRouteImport.update({
  id: '/juegos',
  path: '/juegos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ejercicios': typeof EjerciciosRoute
  '/foro': typeof ForoRoute
  '/juegos': typeof JuegosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ejercicios': typeof EjerciciosRoute
  '/foro': typeof ForoRoute
  '/juegos': typeof JuegosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ejercicios': typeof EjerciciosRoute
  '/foro': typeof ForoRoute
  '/juegos': typeof JuegosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/ejercicios' | '/foro' | '/juegos' | '/perfil' | '/ranking'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/ejercicios' | '/foro' | '/juegos' | '/perfil' | '/ranking'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/ejercicios'
    | '/foro'
    | '/juegos'
    | '/perfil'
    | '/ranking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EjerciciosRoute: typeof EjerciciosRoute
  ForoRoute: typeof ForoRoute
  JuegosRoute: typeof JuegosRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejercicios': {
      id: '/ejercicios'
      path: '/ejercicios'
      fullPath: '/ejercicios'
      preLoaderRoute: typeof EjerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foro': {
      id: '/foro'
      path: '/foro'
      fullPath: '/foro'
      preLoaderRoute: typeof ForoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos': {
      id: '/juegos'
      path: '/juegos'
      fullPath: '/juegos'
      preLoaderRoute: typeof JuegosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EjerciciosRoute: EjerciciosRoute,
  ForoRoute: ForoRoute,
  JuegosRoute: JuegosRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
